### ISSUE TITLE
Rebuild jamstats webui with templates

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#105]
Jamstats webui is ugly and coded unsustainably. Rebuild it with HTML templates.

**Comment by dhmay** [comment]
@bullseye555 I made a bunch of changes to the web interface. Mostly, it was about making the code more sustainable, but I think it looks a lot better, too.

Would you mind taking a quick look to make sure I didn't break anything? I tested it out with a scoreboard server running on my machine, but I have a history of missing stuff.

If you have any suggestions for UI tweaks, now that I've reorganized the code, it's a lot easier for me to spruce things up.

**Comment by bullseye555** [comment]
Bad news, @dhmay ...
Using asset at https://github.com/dhmay/jamstats/actions/runs/4212285012 
![image](https://user-images.githubusercontent.com/28804763/219907766-1075923b-d46c-4979-8fa2-bbf57bc7afa7.png)

```
Traceback (most recent call last):
  File "flask\app.py", line 2551, in __call__
  File "flask\app.py", line 2531, in wsgi_app
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 1825, in full_dispatch_request
  File "flask\app.py", line 1823, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "jamstats\web\statserver.py", line 163, in index
  File "flask\templating.py", line 146, in render_template
  File "jinja2\environment.py", line 1081, in get_or_select_template
  File "jinja2\environment.py", line 1010, in get_template
  File "jinja2\environment.py", line 969, in _load_template
  File "jinja2\loaders.py", line 126, in load
  File "flask\templating.py", line 62, in get_source
  File "flask\templating.py", line 98, in _get_source_fast
jinja2.exceptions.TemplateNotFound: jamstats_gameplots.html

```

**Comment by dhmay** [comment]
Dang! Ok, sorry, I'll make sure I have it basically working before I ask you to check it again.

**Comment by bullseye555** [comment]
All good!

**Comment by dhmay** [comment]
@bullseye555 
OK, that took a lot of trial and error, but I think I've got it! Please have another go with the latest build artifact.

**Comment by bullseye555** [comment]
Looks good now! But did find a quirk that I'll lodge another bug for (something I hadn't tested for before, sorry!)

**Comment by bullseye555** [comment]
when testing #108 , I noticed this - I can't remember if it was there before or not, but looks like on PC it's not resizing some of the screens

PC:
![image](https://user-images.githubusercontent.com/28804763/221436255-9223b0a7-6ef5-435d-a09e-a5877c25b13d.png)
Tablet
![Screenshot_20230227-074022_Chrome](https://user-images.githubusercontent.com/28804763/221436303-920d32db-aca7-4281-908f-cf6b4b9ac72a.jpg)

The Jammer Summary looks ok
PC
![image](https://user-images.githubusercontent.com/28804763/221436346-ec664541-917b-4fcc-97d4-5e0ed61457c5.png)
Tablet
![Screenshot_20230227-074028_Chrome](https://user-images.githubusercontent.com/28804763/221436356-640de78f-28ba-42f4-995e-1f9b42e2795a.jpg)

**Comment by dhmay** [comment]
Interesting. I wonder if that's a browser settings thing, because that's not the behavior I get. But I should be able to code defensively to avoid it. Unfortunately, I'm no kind of web developer, but I'll give it a shot!

**Comment by bullseye555** [comment]
Thanks - It's not the be-all and end-all if you can't, I just thought it'd be one of those things where a use-case would be to have an auto-revolving page [something like Auto-Tabs for Chrome] on a PC screen where it'd be difficult to see the data 
It's a pretty small edge case, as I'd realistically foresee it being used on a tablet during the game, so...

**Comment by dhmay** [comment]
Just to be clear on the expected behavior... what I want to happen, and what happens on my laptop, is:
* the width of the sidebar stays constant
* the width of the image resizes with the window

So, if you want the full image to fit on your screen without scrolling, you can get that by narrowing the window. That way, very vertical images like the Lead and Scores plot can be large enough to be legible, or small enough to fit on your screen, up to you.

Is that what's happening for you? If so, what do you think would be better behavior?

**Comment by dhmay** [comment]
I could add some kind of control to optionally keep the height of the image constrained, as well as the width.

**Comment by dhmay** [comment]
I changed the behavior a bit... is this better?

**Comment by bullseye555** [comment]
> ust to be clear on the expected behavior... what I want to happen, and what happens on my laptop, is:
> 
> the width of the sidebar stays constant
> the width of the image resizes with the window
> So, if you want the full image to fit on your screen without scrolling, you can get that by narrowing the window. That way, very vertical images like the Lead and Scores plot can be large enough to be legible, or small enough to fit on your screen, up to you.
> 
> Is that what's happening for you? If so, what do you think would be better behavior?

I'm not getting any re-sizing of the image in the asset from #108 

>I changed the behavior a bit... is this better?

From the updated asset with push #290 it looks like there's a minimum size to the plots - I think this should be fine.

The only recommendation I'd make so that there doesn't need to be as much vertical space required is to move the info box under the logo
![image](https://user-images.githubusercontent.com/28804763/221772098-e287fce1-fd3b-4347-85e3-420c2c398d59.png)

**Comment by dhmay** [comment]
OK, cool, I'm going to close this and fold it into another issue I'm about to open. This is going to be pretty sweet....
