### ISSUE TITLE
[BUG] Expulsion penalty being included in penalty count

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#107]
**Describe the bug**
When an expulsion or Foul Out is recorded, the Foul Out or Expulsion is being counted when it shouldn't be

**To Reproduce**
Use the EXP/FO column in CRG to mark a skater as Expelled or Fouled Out

**Expected behavior**
Penalty in EXP/FO column doesn't count towards total penalties count

**Screenshots**
![image](https://user-images.githubusercontent.com/28804763/220072744-8377ca32-6c02-40d6-8d22-ff75c38d057d.png)

**Comment by dhmay** [comment]
Thanks for finding that! Presumably this is with a live scoreboard connection? Does the same thing happen if you save the end-of-game JSON and make plots from it? If so, please send me that. Presumably, FO is getting logged as a penalty (and as the same type of penalty that triggered the FO) but somehow I'm supposed to know not to count it twice.

**Comment by bullseye555** [comment]
>Presumably this is with a live scoreboard connection?

Correct

Let me dummy up a game that has the expulsion and I'll get confirm and get the JSON to you here

**Comment by bullseye555** [comment]
I even did this as a PDF output! :P 

Confirming that a JSON shows the double up. 

PDF and JSON attached
[BvW.pdf](https://github.com/dhmay/jamstats/files/10787909/BvW.pdf)
[STATS-2023-02-20_Black_vs_White.json.txt](https://github.com/dhmay/jamstats/files/10787910/STATS-2023-02-20_Black_vs_White.json.txt)

![image](https://user-images.githubusercontent.com/28804763/220201428-c187254a-07bf-4be0-8639-b0dc43f52f1d.png)

**Comment by dhmay** [comment]
Interesting! The back block is definitely in the JSON twice -- as it would have to be, since that's how Jamstats is counting it twice. Here's the relevant json:
```
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).JamNumber" : 2,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Next" : "",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Number" : 0,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).PeriodNumber" : 1,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Previous" : "",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Readonly" : false,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Served" : true,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Serving" : false,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(0).Time" : 1676886717167,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).BoxTrip" : "",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Code" : "B",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).ForceServed" : true,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Id" : "2a855c83-9239-4bbb-b4e6-2923373648b9",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Jam" : "06af213f-a7db-495d-9b9d-b849bcb638d7",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).JamNumber" : 2,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Next" : "",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Number" : 1,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).PeriodNumber" : 1,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Previous" : "",
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Readonly" : false,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Served" : true,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Serving" : false,
    "ScoreBoard.Game(f2026c86-548b-4aaa-b85b-37ff261c8e4b).Team(1).Skater(43b1985b-92fc-47c5-9e5f-66c3ffeba51d).Penalty(1).Time" : 1676886688428,
```

**Comment by dhmay** [comment]
@ frank-weinberg could I get your advice, please? One of the penalties above is "real", and the other seems to be generated when the skater is marked as Foul Out. 

It seems like the "right" thing to do is count the first one but not the second, but, looking at the json, I'm not sure I can find a principled way to do that. Each "penalty" gets a unique ID, they're both marked as "Served", and I can't see anything else obvious to distinguish them.... they both look "real" to me.

I could try some kind of hack of not allowing a skater to accrue two of the same kind of penalty in the same jam within a certain time period, but that seems dangerous. Is there a better way?

**Comment by dhmay** [comment]
Hm, I do notice that Penalty(1) is has a lower "Time" than Penalty(0). Is that a clue?

**Comment by bullseye555** [comment]
@dhmay - This was also a bug in the Penalty Display at one point in CRG

Not sure if https://github.com/rollerderby/scoreboard/issues/528 with pull https://github.com/rollerderby/scoreboard/pull/531 are any help on how it was interpreted ?

A _really_ quick look at the commit and JS ([here](https://github.com/rollerderby/scoreboard/blob/dev/html/components/plt-input.js)) [I don't know JS, but a quick interpretation of variables etc...] suggests that it's excluding Penalty(x).Number = 0

Please don't take my word for it, double check and we'll see if Frank has any feedback

**Comment by dhmay** [comment]
Neat! Thanks for pointing me to that. I poked through other JSON files I have lying around, and I didn't see Penalty(0) in any of them. So it does look like Penalty(0) is generated by this kind of event and not by regular penalties. I'll see if I can get that behavior working.

**Comment by dhmay** [comment]
Fixed, please check the latest build. I verified one of my files without foulouts looks fine, and your file loses the second back block.

**Comment by bullseye555** [comment]
Looks good. I also found a JSON where we had a couple of Foul Outs and can confirm that's handling ok too

Keep these on hand - between them, they'll have a little bit of everything (just no expulsions... lol)
[STATS-2022-10-01_Sabres_vs_TheThunder.json.txt](https://github.com/dhmay/jamstats/files/10790330/STATS-2022-10-01_Sabres_vs_TheThunder.json.txt)
[STATS-2022-11-26_WestsideRollerDerby_vs_PotLuck.json.txt](https://github.com/dhmay/jamstats/files/10790332/STATS-2022-11-26_WestsideRollerDerby_vs_PotLuck.json.txt)

**Comment by frank-weinberg** [comment]
Just to confirm what you already figured out: Penalty(0) is foul out/expulsion and should not be included in the count.
