### ISSUE TITLE
Add "most recent penalties" table for live games

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#108]
Add a table to help announcers find the most recent penalties called. Show the most-recent X penalties (10?), with the fields:

jam #, time in jam, team, skater number and name, penalty type

with each row colored by team color.

**Comment by dhmay** [comment]
Possibly, should refresh the page more often if you're looking at that table.

**Comment by dhmay** [comment]
@bullseye555 When you have a chance, please check out the new "Recent Penalties" link in the live web interface. It should give you a table of the 10 most recent penalties -- I hope it doesn't break in weird live-game situtations!

Also, I could use some help optimizing it:

* the "Served" and "Serving" columns are from the scoreboard json I get for each penalty. Do you know exactly what those mean?
* what do you think about the columns I'm showing, and the column order?
* I'm definitely planning to add team colors to the rows
* Any other suggestions?

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/714077/221112879-31cfc646-efb4-4823-ae76-b43899685add.png">

**Comment by bullseye555** [comment]
Before downloading, here's my comments

>the "Served" and "Serving" columns are from the scoreboard json I get for each penalty. Do you know exactly what those mean?

Basically, is the skater in the box. This could be consolidated to a single column representing the status, rather than multiple columns. The logic should apply as follows:
- Served & Serving = False then **Not yet reported**
- Served = False & Serving = True then **Skater serving penalty**
- Served = True [Serving status irrelevant] then **Penalty completed**

>what do you think about the columns I'm showing, and the column order?

Love that most-recent is at the top. 
Is _Team 1_ / _Team 2_ going to be the actual Team Name?
Would probably have the skater number in there somewhere, too
I'd probably put the Team, Skater, and Penalty as the first 3 columns though
- Option 1 (if you can concatenate the Number & Skater)
Team, Number & Skater (eg: **813 Bullseye**) , Penalty, Status, Period, Jam

- Option 2 (If you can't)
Team, Number, Skater, Penalty, Status, Period, Jam

>I'm definitely planning to add team colors to the rows

Love the idea. Suggest having a default just incase colours aren't loaded (eg: White & Light Grey alternating?)
Should definitely have a bottom boarder between each row, just to make it obvious it's a new row

>Any other suggestions?

Hopefully the above suggestions help - will check it out soon, and will let you know if there's any bugs or other suggestions

**Comment by bullseye555** [comment]
![image](https://user-images.githubusercontent.com/28804763/221139665-fc364d21-e9fa-44aa-a9e9-0806fccb84d9.png)
Sorry @dhmay - fails to get data from scoreboard

**Comment by dhmay** [comment]
Sorry about that, @bullseye555 ! I hadn't addressed the case where there were no penalties yet. Please try again!

**Comment by bullseye555** [comment]
All good! Working now!

Updated logic for Served status after seeing what they are [counter-intuitively, Served is set as **True** before the penalty has actually been served]
- Served & Serving = False then **Not yet reported**
- Served = True & Serving = True then **Skater serving penalty**
- Served = True & Serving = False then **Penalty completed**

The other thing I'd suggest including is a reference to any Foul-Out or Expulsion
If someone got more penalties that the ruleset allowed, note that it's a Foul Out
Looking at the JSON data it looks like the value is in 
"ScoreBoard.CurrentGame.Rule(Penalties.NumberToFoulout)"
So logic would be if skater count of penalties is equal to or greater than that value, it's a foul out

Expulsion:
EG: Number 166 for this team committed a Gross-Misconduct penalty and was expelled from the game 
![image](https://user-images.githubusercontent.com/28804763/221341712-c34248d0-3a3f-4428-b3b3-fc3b08d727c7.png)
I would add a note that this was an _Expulsion_ [use the _Penalty(0)_ from #107 that was identified as the Penalty for FO/EXP and if count of penalties is less than that value, it's an expulsion]

@frank-weinberg - I can't see anything in https://github.com/rollerderby/scoreboard/wiki/WebSocket-Channels that confirms this node is expected to be there, but from my testing it appears to be there all the time, can you confirm?

**Comment by frank-weinberg** [comment]
This logic is broken - Penalty 7 may be an expulsion but would be considered an FO by this.
Check `Penalty(0).Code` instead - A code of `FO` means foul out, any other code means expulsion.

**Comment by bullseye555** [comment]
Valid point - good pick up thanks @frank-weinberg

Can you confirm on _ScoreBoard.CurrentGame.Rule(Penalties.NumberToFoulout)_ being the correct node to check for current game?

**Comment by frank-weinberg** [comment]
Yes, that is the value used to check if a skater has fouled out internally.

**Comment by dhmay** [comment]
I haven't done anything about foulouts or ejections yet, but what do you think about the table contents, layout and colors, @bullseye555 ?

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/714077/221382304-3285758c-3f8f-444b-a2dd-036c5cb22190.png">

**Comment by dhmay** [comment]
(if either team is white, background will be gray. If gray plays white, tough luck)

**Comment by dhmay** [comment]
(third possible value for "Status" is "Serving")

**Comment by dhmay** [comment]
Oh! That's weird... I *did* implement "<number> <name>" in the "Skater" column, but it doesn't play nice with my anonymizer function. Anyway, check it out on your data, it should work fine.

**Comment by bullseye555** [comment]
Using asset at https://github.com/dhmay/jamstats/actions/runs/4272464938 _Visual Tweak_ #282
![image](https://user-images.githubusercontent.com/28804763/221385934-cccbb1ef-8757-4df5-9e41-9d360543fea4.png)
```
Traceback (most recent call last):
  File "flask\app.py", line 2551, in __call__
  File "flask\app.py", line 2531, in wsgi_app
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 1825, in full_dispatch_request
  File "flask\app.py", line 1823, in full_dispatch_request
  File "flask\app.py", line 1799, in dispatch_request
  File "jamstats\web\statserver.py", line 201, in index
  File "jamstats\plots\jamplots.py", line 155, in get_recent_penalties_html
AttributeError: 'tuple' object has no attribute 'lower'
```

If I go back to improvements to recent penalty table #278 I get the same thing
https://github.com/dhmay/jamstats/actions/runs/4272097461

**Comment by dhmay** [comment]
Huh! That's weird (because it doesn't happen to me), but it's because of my "what to do if a team color is white" code, so I commented that out for now. Should work.

**Comment by dhmay** [comment]
As a bonus, I added rosters for both teams.

**Comment by bullseye555** [comment]
Initial test looks good - I'll want to have a look later in the day to see how it goes with teams with colours. Picked up a couple of things though, will raise in appropriate places
