### ISSUE TITLE
Add game-day roster management to webserver

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#116]
Build a tool for managing rosters on game day: 

* add a dropdown by each skater's number/name to indicate whether they're present and skating, present and not on skates, or absent
* add a mode that just shows the skaters who are present, separated by whether they're on skates or not

**Comment by bullseye555** [comment]
CRG already supports this (to an extent)
Not sure the field in the JSON, but the status' are:
- Skater
- Not Skating
- Captain
- Alt Captain
- Bench Alt Captain
- Bench Staff

**Comment by dhmay** [comment]
Whoah! @erevrav , did you realize that? 

I still think it would be helpful for Jamstats to provide a view, since Jamstats is providing an announcer platform. Easier to hit one site than two, especially when you're setting something up for someone who's not in close communication with the NSO group.

**Comment by bullseye555** [comment]
I wouldn't try to reinvent the wheel with this one - having a screen for Commentators? Brilliant idea - but I'd leave the management of who is skating etc to the Scoreboard, as the NSO crew will (or at least should...) have the most up to date information around who is skating and who isn't
(this is coming from me as the head official for my league, having THNSOd more than a handful of tournaments, and a Certificate WFTDA NSO)

JamStats is going to HAVE to be managed by the team running the tournament/game(s), so you don't want to have to update information in two places. And if you pass the responsibility onto the teams to do, then there's every possibility that they forget or just don't care and not do it

Absolutely not _stopping_ your from doing it, but just wanting to make sure you're aware that it might not be as useful as you expect it to be...

**Comment by dhmay** [comment]
In our league, at present, we're missing any formal communication of who's actually present on game day. Our announcer typically *manually* collects lists of who's absent and then, at announcement time, runs down the roster, omitting anyone known to be absent. 

If there's a better way to capture this info, I hope we can move in that direction! Seems tricky, since skaters can trickle in at pretty much any time.

**Comment by dhmay** [comment]
@bullseye555 , how does your league communicate presence/absence to the announcer? Does your announcer have a view on scoreboard-captured attendance info?

**Comment by bullseye555** [comment]
There's a Roster sheet in the IGRF (Paperwork, Statsbook, whatever it gets called - the _Interleague Game Reporting Form_ is what it's officially known as) that gets printed and provided to commentators.

So, while this is technically from IGRF, it's taken from the same data as CRG. 
Any changes that have happened between IGRF being populated and imported to CRG are made in the paperwork before being given to the commentators - but those changes are then ALSO made in CRG to make sure the scoreboard has accurate data

**Comment by bullseye555** [comment]
For clarity, who is and isn't skating is determined at the Captains meeting with the head Ref & NSO prior to game start (when this happens varies by game/tournament but is typically either 30 mins prior to game time, or in the half time of the game before it)

**Comment by dhmay** [comment]
Ah, gotcha. In our junior league we can’t enforce that early decision making, but it still might make more sense to use the same mechanisms for attendance taking rather than implement something separate.
________________________________

**Comment by bullseye555** [comment]
Yeah, that makes sense
