### ISSUE TITLE
Jamstats server doesn't work on some versions of Windows

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#120]
**Describe the bug**
As described [here](https://github.com/dhmay/jamstats/issues/111#issuecomment-1465182394), on some computers, Jamstats server won't run. Could possibly be related to Windows version -- the two computers it wouldn't run on were Windows 10 and 11.

**Comment by bullseye555** [comment]
Updated info:
[This artifact](https://github.com/dhmay/jamstats/actions/runs/4422888325) ran on WinServer2019 no issue
Trying to run it on Win11  I was able to open and run the GUI config, and run via command line, but it didn't appear to start a WebServer [normally I get the Windows _User Access Control_ asking me if I want to allow the program through the firewall - I did not get that in this version
```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎11/‎10/‎2022
OS build	22621.1344
Experience	Windows Feature Experience Pack 1000.22639.1000.0
```
Log file (taken from Windows Powershell), Win11:
[JS Log - Win11.txt](https://github.com/dhmay/jamstats/files/10977483/JS.Log.-.Win11.txt)

Running on Win10 
```
Edition	Windows 10 Home
Version	22H2
Installed on	‎09/‎06/‎2022
OS build	19045.2604
Experience	Windows Feature Experience Pack 120.2212.4190.0
```
Log file (taken from GUI log window, Win10:


The one main difference between this version and the previous ones, is that the previous versions would continue attempting to connect to the server but never loads (and did the Windows UAC request for Firewall permissions) [like it's waiting for data to be provided, but the WebServer never outputs anything] - in this, it just doesn't start the WebServer, so has nothing to connect to and times out
![image](https://user-images.githubusercontent.com/28804763/225251561-4b60cb5f-54c2-4216-9f53-2ca3c7ed02e1.png)

**Comment by bullseye555** [comment]
And just to make sure it wasn't some weird inter-dependency where JS was using CRG resources on a local machine (implausible I know, but I want to make sure I do as much debugging for you as I can!), I even installed and ran CRG on both W10 and W11 machines, then re-ran JS via GUI and CMD with no luck

**Comment by dhmay** [comment]
OK, @bullseye555 , I think I fixed this in the latest merge. It wasn't working on my Windows 11 box, and now it is. I also made the messages less verbose. So, after you start up Jamstats and enter your args in the GUI, the last message you see (if you're not in debug mode) should be where to point your browser.

Please confirm! If this is working, I'm going to put out a new release, aimed at announcers, and tell the scoreboard FB group about it.

**Comment by bullseye555** [comment]
Mixed success using [385c524](https://github.com/dhmay/jamstats/commit/385c52477a93cd5304a025d600b1f4fd0aad3c8c)

It's loading at localhost:#### but not at myipaddress:#### (and can't access from other devices)
![image](https://user-images.githubusercontent.com/28804763/226730381-601505e0-a236-45b7-a957-7a14e99b36df.png)

BUT 

If I change the _jamstatsip_ to the IP address and restart JamStats, I can then hit JamStats at myipaddress:#### but not at localhost:#### (and it can be accessed from other devices, too)

**Comment by dhmay** [comment]
Hey hey! From my perspective that's not mixed success, that's just success! 

You have to pick whether to bind to localhost (and so no traffic goes out over your network) or to your IP address on the network (and so your traffic all goes out over the network). 

The reason I changed the default to localhost is that, at our track, the wifi connection to the scoreboard is really tenuous, and our announcer was running Jamstats on the same machine she was viewing it on. 

Would it be helpful to have another mode where you didn't have to specify your network IP but it bound to it anyway and told you what it was?

**Comment by dhmay** [comment]
I added that to the readme and the pdf doc.

**Comment by bullseye555** [comment]
Perfect!
