### ISSUE TITLE
[FEATURE REQUEST] - Officials Roster

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#122]
**What version of the tools are you running, and how?**
1.0.2 from artifact at push 354 https://github.com/dhmay/jamstats/actions/runs/4422888325

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
On the _Roster_ screen, include the roster of Officials, as extracted from CRG
![image](https://user-images.githubusercontent.com/28804763/225246236-70c66d67-ddd6-432a-9cef-8a7e0f02b732.png)
(Yes, I only had 4 Refs for this game... A no Penalty / Lineup trackers....)

**Describe alternatives you've considered**
This is currently printed as part of the _Rosters_ generated and printed on the IGRF, so if we're aiming to replicate (replace?) that, we'll want to include Officials too

**Additional context**
I don't see any need to include what team they're doing what for (most of the time, this will be done POST game anyway, it's only when your HNSO is the SBO like I was for this that it'd be done before the game). 
JSON location is _ScoreBoard.\*.Nso(\*).Name_ and _ScoreBoard.\*.Nso(\*).Role_

**Comment by dhmay** [comment]
Oh, interesting! I assume that'll be pretty easy to do, but it's a part of the JSON I haven't touched yet. I'll give it a go.

I'm thinking maybe have it on a separate "Officials Roster" page, to keep down clutter / minimize scrolling. Make sense to you?

**Comment by bullseye555** [comment]
Yeah, makes sense - I think that'd be ok as a new page

**Comment by dhmay** [comment]
Looks like SOs are in the JSON as "Ref(" and NSOs are in there as "Nso("

**Comment by dhmay** [comment]
@bullseye555  look good to you?

**Comment by bullseye555** [comment]
Doesn't look like it's linked to from the menu? 

I used the asset from [13be441](https://github.com/dhmay/jamstats/commit/13be441828f8320825056439d15dd242b0005357) and can see the changes in the code, but can't work out what the **?plot_name** should be to view it

![image](https://user-images.githubusercontent.com/28804763/226094563-fcac7202-fe9e-4330-a07d-72ceeaea2f7c.png)

And the _Roster_ only has the teams on it
![image](https://user-images.githubusercontent.com/28804763/226094633-a38a8299-f694-4ea6-acf0-3c5018d8ca3e.png)

(Suggest having the name of the link when you add it to be **Officials Roster** and updating the **Roster** to be **Team Roster**)

**Comment by dhmay** [comment]
Latest build artifact (main branch) improves the looks:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/714077/226124548-4c480ac5-d966-4250-b4c5-6b9289386a63.png">

**Comment by bullseye555** [comment]
Weird... Using [0c4e2a6](https://github.com/dhmay/jamstats/commit/0c4e2a64ad0802e739b74024e49c990c1e6594b9) it shows

Looks good - definitely prefer the second one with no outside lines
