### ISSUE TITLE
Jamstarts fails to respond to new game started after previous game finishes

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#123]
**Describe the bug**
From @bullseye555 , reported in issue #118 :

```
I then Finished the DCRD/NERD v TVC game and started a new one (KCR v WSRD) and the Finished game remained on screen and never refreshed.
When I tried to change a page, all I got was a "Waiting for ..." message from my browser
```

**Comment by dhmay** [comment]
[Link to original note](https://github.com/dhmay/jamstats/issues/118#issuecomment-1469528705)

It looks like JS picked it up, and reported "New Game!" with the new game ID. But UI didn't update. Stopping and restarting JS works around the issue.

**Comment by dhmay** [comment]
Fixed! Please give it a go, @bullseye555

**Comment by bullseye555** [comment]
Works great - as soon as the New Game is triggered in CRG, the refresh happens in Jam Stats
