### ISSUE TITLE
Make Jamstats independent of an internet connection

### ISSUE THREAD

**Issue by blauwblaatje** [dhmay/jamstats#129]
**What version of the tools are you running, and how?**
Windows and Jamstats For Announcers

**Is your feature request related to a problem? Please describe.**
I was running Jamstats on a closed network, so without an internet connection. It took a long time for Jamstats to load as it was trying to connect to a cloud provider.

**Describe the solution you'd like**
Include external assets in the build

**Describe alternatives you've considered**
Alternative would be to always have an internet connection, but that's not always possible. For instance, we run an internal network for SB and tablets, so we're not dependent on crappy venue wifi

**Additional context**
I must say, I haven't dug deep into the issue. I saw it was loading very slow and saw it was trying to connect to a cloud provider (can't remember which one) for some assets. But I was busy doing other things and didn't have time to check it out completely.

**Comment by dhmay** [comment]
Thanks for that idea! I've been concerned about the increase in startup time for Jamstats as I've added more and more dependencies to it (particularly to support websockets). I assumed that was the main thing slowing it down, the size of the package. 

But I'm intrigued about the idea that it might be trying to reach outside resources that's slowing it down! Do you notice that Jamstats is much faster to start up when you have an internet connection? I'll start playing with startup time with/without a connection, too, and see if there's anything I can do to speed it up.

**Comment by dhmay** [comment]
Hmm, @blauwblaatje , can you give me a few more details about when loading Jamstats is slow? 

When do you notice the slowdown? Is it before the parameter screen comes up? After the parameter screen, before Jamstats tells you where to point your browser? Or in the browser itself?

Also, how do you know Jamstats is trying to connect to cloud services?

I just tried running the Windows executable while connected to a network, and it took about 20 seconds to start up (to the enter-parameters screen). Then I turned off my wifi and did the same thing, and it still took about 20 seconds. Slower than I'd like, but it didn't seem to be related to network connection.

**Comment by dhmay** [comment]
Good, the script I needed was covered under an MIT license, so I added it to the codebase, along with its license. Easy fix.

@blauwblaatje , this issue should be fixed in the latest build file: 
https://github.com/dhmay/jamstats/suites/11864792697/artifacts/620376427

Download that and unzip it -- it contains a new jamstats.exe. Would you mind verifying the fix for me? I'd love to get some external confirmation that it works now. This is an important enough bug that I want to make a new release for it ASAP.

**Comment by dhmay** [comment]
@erevrav There's a 100% chance this bug explains the problems I was having getting Jamstats on the Surface to auto-update with the scoreboard, during the last games, when it worked fine on my laptop.

**Comment by erevrav** [comment]
heckyeah -- that's super to hear! I'm in the process of setting up a replacement wireless network for our venue right now (that will also be disconnected from the internet), and once it's running I'll confirm the fix in the new artifact.

**Comment by blauwblaatje** [comment]
Confirmed.  I was offline and it loaded very quickly.  Thank you!

**Comment by dhmay** [comment]
Woohoo! I'll put out a new release right away.

**Comment by erevrav** [comment]
(took a while, but I confirm, too. 

I had temporarily broken the "new," hand-me-down wifi, but I restored to factory & finally got it running. jamstats runs & shows the websocket-powered updates super quickly.)
