### ISSUE TITLE
Add an Announcer Dashboard interface

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#136]
**What version of the tools are you running, and how?**
All

**Is your feature request related to a problem? Please describe.**
The most useful announcer interface seems to be Current Skaters, but there are other useful bits of information it'd be helpful to see without clicking back and forth

**Describe the solution you'd like**
We'll develop ideas here in this issue. For starters:

* current skaters (just this jam, not previous, for space)
* a subset of the Teams Summary table stuff... whatever you think would be most useful. Maybe Score, Lead, Total Penalties...?
* anything else? I could give you basic stats for the current jammers, e.g.

**Comment by dhmay** [comment]
Proposal:
<img width="887" alt="image" src="https://user-images.githubusercontent.com/714077/229369130-5f4dc205-8fa4-4284-b9ce-436563f3b075.png">

**Comment by ScottChicken** [comment]
Interesting weirdness when I have the window (Chrome) not full width: The collapsible left menu is showing up on top and pushing the other stuff to the bottom. Not necessarily a bad thing once I figured it out, but when I first launched the window and saw this I thought things were broken (until I scrolled down)
![image](https://user-images.githubusercontent.com/129686057/229370807-d40411e7-9417-45e1-9037-30a8b1ca9736.png)

**Comment by ScottChicken** [comment]
Also: looks like when the screen refreshes to grab the new data it's popping the collapsed menu back up, so pushing things down below.

**Comment by dhmay** [comment]
Thanks for that report. I did my testing in Firefox, and I'm not a fantastic web dev. I'll fix it up for Chrome.

**Comment by dhmay** [comment]
Hm, I can't reproduce in Chrome... if I squish it down I get stuff like this:
<img width="770" alt="image" src="https://user-images.githubusercontent.com/714077/229373215-da439ded-84ef-48b5-a353-45a6cfe1ff13.png">

I'll fix up those glitches and hopefully it'll deal with what you're seeing, too.

**Comment by dhmay** [comment]
This build fixes the issue where all the data moves down below the left sidebar if you make the window too skinny:
https://github.com/dhmay/jamstats/actions/runs/4590900794

Closing this issue. Remaining enhancements are in the other one.
