### ISSUE TITLE
Add penalty comparison

### ISSUE THREAD

**Issue by ScottChicken** [dhmay/jamstats#146]
**What version of the tools are you running, and how?**
1.2.1

**Describe the solution you'd like**
Create team penalty comparison - could be a table or a plot
- Compare both teams - team 1 on the left, team 2 on the right
- Total penalty count should appear at the top, possibly next to the team name above the table/plot
- Plot or table should have skater name and number, then total penalty count
   - If you build it as a plot, the total number should be visible along with the bar indicating the count
- Plot or table should use coloring to indicate the skater's total penalty status
   - Black text / green bar for 0-4 penalties
   - Black text / yellow bar (or yellow background) for 5 penalties
   - Black text / orange (amber?) bar / background for 6 penalties
   - Red text / bar for 7 penalties

For this comparison the TYPE of penalty isn't as important as the count - idea is to quickly see who on which team is in trouble of fouling out, what the total counts are, etc.

**Comment by dhmay** [comment]
Is this request basically for the "Penalties by skater" plot from the [Skater view](https://github.com/dhmay/jamstats/blob/main/resources/skater_stats.png), except not broken up by penalty, and showing both teams, and with the other features you requested?

Should the penalty count bars maybe be vertically oriented (i.e., the opposite of the current orientation)?

**Comment by ScottChicken** [comment]
Yeah, it's basically the penalty sheet but with both teams. Again, could easily be a table with three columns for each team - skater #, skater name, total # of penalties. Could go off the overall roster (so skaters with no penalties are on the list but don't have a number) or could populate once a skater gets a penalty - whichever is easiest.

But the Skater view plot would work if it had both teams side by side with a "team total" at the top, the count (so I don't have to look down to figure out how far across the plot I am) and probably without the jam-based info (don't care about the # of jams or the penalties per jam).

**Comment by dhmay** [comment]
Working on this now, @ScottChicken ... what order would you like the skaters in? Derby order by number, or descending penalty count order? And do you want the skaters with no penalties on this plot?

**Comment by dhmay** [comment]
Oh, I see, regarding skaters with no penalties you already told me either way is fine. I'll leave them out. Two questions, then:

* Derby order by number, or descending penalty count order?
* You suggested a different color scheme for indicating penalty count visually. I'll implement that here. Would you like that same color scheme on the Caller Dashboard, or should I leave that as-is?

**Comment by dhmay** [comment]
Oh, I get it, now. Your color scheme assumed a plot. Since I'm implementing this as a table rather than a plot, I've only got background color and text color to work with, no bar. So I'm thinking I'll use the same approach to color I used on the Caller Dashboard. Sound good, or would you rather the text be black and the background color change?

**Comment by dhmay** [comment]
Here's how it looks currently:
<img width="656" alt="image" src="https://github.com/dhmay/jamstats/assets/714077/eafb1666-ce96-4e52-b38c-591156bc10c8">

(I'll fix the table alignment)

**Comment by dhmay** [comment]
I could leave it like that, or change the colors of all the text to match penalty count, or make the text black and change background color instead.

**Comment by ScottChicken** [comment]
That was a journey! Yes to the number order, and the color on the text is
probably good as long as the lightest one is readable. Might make the whole
row that color rather than just the penalty count?

**Comment by dhmay** [comment]
Here's how it looks. I'll bundle your feature requests into a new release in a bit.
<img width="607" alt="image" src="https://github.com/dhmay/jamstats/assets/714077/768a4c73-30b1-4790-86ac-7ecf1e6155b8">

**Comment by dhmay** [comment]
Ah, good, I was able to fix a problem that was keeping JamStats from building. @ScottChicken , please grab [this build](https://github.com/dhmay/jamstats/actions/runs/5237913539) and check out the "All Penalties" table.
