### ISSUE TITLE
Add skater pronouns to roster

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#150]
Skater pronouns are available in JSON entries like this:

`"ScoreBoard.CurrentGame.Team(x).Skater(id).Pronouns"`

It should be pretty easy to capture those and add them to the roster table.

**Comment by dhmay** [comment]
@bullseye555 You mentioned the Pronouns lines (e.g., above) in the JSON file, but I don't have any JSON files with those lines ending in .Pronouns. Were they an addition in a recent CRG release?

Could you please send me a file (here or in Facebook) with those Pronouns lines, so I can make sure my enhancement works?

**Comment by bullseye555** [comment]
Yeah, they were added pretty recently - I'll mock up a JSON for you later
today and attach to this ticket

**Comment by bullseye555** [comment]
[scoreboard-0-secs-ago.json.txt](https://github.com/dhmay/jamstats/files/11769909/scoreboard-0-secs-ago.json.txt)
Mock up with a couple of jams - hope this is enough

**Comment by dhmay** [comment]
Oh, dear. JamStats failed hard on that file, because it doesn't have this JSON key:

ScoreBoard.State

I have a hard dependency on that key, which tells me whether the game is in progress, or over, or what. So, the question is, did that key not get into the file because of the way the file was generated, or is that key no longer in the latest version? 

If the former, I should dummy it up and work around it. If the latter, then the format has changed and I need to deal with *that*. Do you know which it is?

**Comment by dhmay** [comment]
Hm, actually, never mind, that's not what's giving me trouble. I'll keep looking at that file....

**Comment by dhmay** [comment]
Ahhhh, it's because the version is now "v2023". Is that a real thing? The numbering scheme is changing to year? Anyway, I'll need to future-proof against versions that aren't 4 or 5. I'm so glad you sent me that file!

**Comment by erevrav** [comment]
Yes, in May the version number format changed from 5.0.11 to 2023.0. (As an SBO, this was a little jarring, but I get the rationale.)

**Comment by dhmay** [comment]
OK! Pronouns and v2023 compatibility are both implemented in [this build artifact](https://github.com/dhmay/jamstats/actions/runs/5299561563). Here's what the table looks like with pronouns:
<img width="556" alt="image" src="https://github.com/dhmay/jamstats/assets/714077/2097e072-0972-4893-bc7e-173f572d0188">
(Column headers "Black Skaters" and "White Skaters" are an unfortunate consequence of the teams being named "Black" and "White" in the source json file)
