### ISSUE TITLE
Switching stats/plots with multiple clients refreshing

### ISSUE THREAD

**Issue by blauwblaatje** [dhmay/jamstats#169]
**Describe the bug**
When multiple clients are looking at the same instance, and you switch between stats/plots, a different client sees that plot for a moment when the refresh hits.

**To Reproduce**
1) have multiple clients (I think we had 5 at the same time) connect to jamstats' http server
2) put client 1 on the caller dashboard
3) click through the stats on client 2
4) client 1 will sometimes see the stats that client 2 was requesting 

**Expected behavior**
Expected is that is not showing that. 

**Additional context**
This isn't a big issue, it's was just a little bit annoying

**Comment by dhmay** [comment]
Ha, that's great! I mean not great that the bug exists, but great that you're using JamStats in a way I totally didn't anticipate. The behavior you're seeing makes sense, and I should be able to fix it without ripping up too much code. If it's not a big issue I'll just plan to roll it into the next release with other changes.

**Comment by dhmay** [comment]
Fixed. This'll go into the next release. If you'd like to try the fix out now, you can get the build artifact [here](https://github.com/dhmay/jamstats/actions/runs/6885604679) (scroll down to the bottom, download the zip and unzip it). If you do, please let me know how it goes!
