### ISSUE TITLE
[FEATURE REQUEST] Import and Export functions

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#17]
This is a double-headed request

Would love to be able to see a prompt where the user can enter a file path in plain "file location" logic, eg: **C:\crg\stats\** and have that interpreted by the program and saved as a variable for use when setting the filenames for import/export

Would also like to have a default output filename - if no output filename is given, use the input filename and replace the file extension **.JSON** with the relevant extension for the function called, eg **.PDF** or **.tsv**

**Comment by dhmay** [comment]
Good ideas. I'll pull the file location into an attribute of the DerbyGame object, and I'll add a default output file, used iff the input file has extension .json or .JSON.

**Comment by dhmay** [comment]
OK, I did those two things, in the main branch. If you're working off main, @bullseye555 , you can test it out. If you're using pip you'll have to wait until I release a new minor version... I'm going to bundle a bunch of this stuff together for that.

**Comment by dhmay** [comment]
I'll leave the issue open until it's resolved in a new packaged version, unless you prefer a different strategy.

**Comment by dhmay** [comment]
Fixed in version 0.1.2.
