### ISSUE TITLE
Experience during Holy Duck 2023

### ISSUE THREAD

**Issue by blauwblaatje** [dhmay/jamstats#170]
# How are you using Jamstats? (announcer assistance, coach info...)
* Announcers. They were very happy about it as they could immediately tell the audience in-house and on-stream who was on track and which penalty they got. Ofc this is also doable with the CRG interface, but this was an easier representation for the announcers.
* Tournament Heads table.  It was one of the screens we had open. It gave a quick overview of the last two jams. The period/jam clock would be interesting to have as well, but I saw there was already an issue for it. 

# What's so great about it?
Apart from what I wrote earlier, I showed it to multiple people including teams and they thought it was great. 

# Is there anything that would make it even better?
I don't at the moment.

**Comment by dhmay** [comment]
Thank you for sharing that experience! That's wonderful. I'm super interested in the idea of tournament heads using JamStats. I could create a view that's oriented around that use case (analogous to the Caller Dashboard) if that would be helpful. 

Other than the period/jam clock (which I'm a little nervous about adding in case it gets slightly off from the scoreboard clock and those seconds matter), are there other things that tournament heads would like to see, or things that could be hidden from their view for simplicity?
