### ISSUE TITLE
jamstats throws an exception with python >= 3.10

### ISSUE THREAD

**Issue by yetzt** [dhmay/jamstats#172]
**Describe the bug**
jamstats throws an exception with python >= 3.10

**To Reproduce**
use python >= 3.10

```
$ pip3 install jamstats
$ jamstats
Traceback (most recent call last):
  File "/usr/local/bin/jamstats", line 24, in <module>
    from attrdict import AttrDict
  File "/usr/local/lib/python3.11/dist-packages/attrdict/__init__.py", line 5, in <module>
    from attrdict.mapping import AttrMap
  File "/usr/local/lib/python3.11/dist-packages/attrdict/mapping.py", line 4, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
```

**Expected behavior**
jamstats executes

**Comment by dhmay** [comment]
Ah shoot. Thanks for reporting that. I think I'd better handle this in a backward-compatible way. Is this time-critical for you?

**Comment by dhmay** [comment]
Fixed, I believe, but I haven't verified it. v1.4.3, now in Pypi, removes the offending dependency on attrdict. But I haven't verified 3.10+ compatibility locally yet. Let me know if it works!
