### ISSUE TITLE
Cannot run on mac 12.0.1

### ISSUE THREAD

**Issue by azrollerderby** [dhmay/jamstats#176]
<img width="289" alt="Screen Shot 2024-03-13 at 10 39 01 PM" src="https://github.com/dhmay/jamstats/assets/163382455/f814de55-3305-4140-ac50-8d084b59eb48">

**Comment by bullseye555** [comment]
Are you able to open an older version of CRG on the same device? Eg, v5.0.4
or v2023.1?
You may need to use the "shift open" trick (hold shift while opening) to
workaround, the same as older versions of CRG

**Comment by dhmay** [comment]
Yep, that's a Mac permissions thing, not specific to JamStats. Your Mac must be set up not to open software from third-party developers. [Here's a writeup](https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) of how to work around this issue.
