### ISSUE TITLE
[FEATURE REQUEST] Additional plotting

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#18]
Would love to see some more specific plotting - in addition to the Game-level data, have some Skater-level data:

- For each Jammer, total points scored; average points per jam; average points gained per jam [eg: Points earned by Jammer minus points earned by other team Jammer when that player is on track]
- For each skater, count of Jams they've been on track; count of penalties; top 1 penalty code (order by penalty code alphabetically if multiple on the same count)

**Comment by dhmay** [comment]
These are both great requests. They're at different levels of difficulty... I have all the data I need already for the first, but I need to scrape more from the JSON for the second.

**Comment by dhmay** [comment]
@bullseye555 - I added the jammer-centric plot, plotting the two things you asked for and also jam count and proportion of jams when the jammer got lead. Let me know what you think.

I merged to main, but I haven't built a new release yet... you can play with the new plots now if you're building from source.
![image](https://user-images.githubusercontent.com/714077/206876739-9f9c5de7-b6b0-46f6-a302-cdd14b90e380.png)

I'll close this request when I add the other plot.

**Comment by dhmay** [comment]
(and, yes, that team's jammers all had non-negative mean net points. They won that one, obvs. :) )

**Comment by dhmay** [comment]
OK, @bullseye555 , now the skater plot has jam count, penalty count, and (alphabetically lowest if tied) top penalty. Included in the new version 0.13.
![image](https://user-images.githubusercontent.com/714077/207248587-f3a3b1d2-757d-4c89-82c1-cc965e05f270.png)

**Comment by bullseye555** [comment]
Thanks @dhmay - have had a look at it tonight and it looks great!

I think the next step is being able to generate this as an output to a webpage - as a permanent addition in CRG

**Comment by dhmay** [comment]
Great! I'm glad they're looking good to you, @bullseye555 . Have you tried generating the plots for an in-progress game by connecting to the scoreboard, or just opening JSONs from disk?

@erevrav and I have also been talking about various things we could do with these plots during a game. I'm thinking about who would want to look at these plots:

* coaches
* fans at the track
* fans at home (we're part of a junior league, so a particular consideration there is parents and grandparents)
* ...?

I'd like to see if I can build a single thing that works for all those people, though that might not play out. In any case, I'm thinking about accessibility from the Internet, not just through the CRG server. One possibility would be to post plots periodically to a social media account. That could get spammy, though.

Another consideration is that I don't know about adding a bunch of burden to the CRV server machine. I don't have direct experience with it, but I've seen a lot of concern about taxing that machine.

I'd love to hear your thoughts about how best to deploy something that people could use to look at these plots. In any case, today I'm going to play with building my PDFs in real time at a running game, and see if there are any kinks in that process to work out.

**Comment by bullseye555** [comment]
_Have you tried generating the plots for an in-progress game by connecting to the scoreboard, or just opening JSONs from disk?_
Only done it from JSON at the moment
I'm on Windows, so your EXE doesn't work for me yet, and my Python is WAAAAAAAY to rusty for me to try and connect live (eg: I only dabbled in it for work for about a couple of weeks before I changed companies and didn't need it any more)

**Comment by dhmay** [comment]
Then you're going to like what I'm working on now. I'm thiiiiis close (I think) to building a Windows executable.

**Comment by bullseye555** [comment]
Most excellent!!

Look forward to seeing it :D
