### ISSUE TITLE
skaters that don't have names in scoreboard should be reported as numbers in jamstats output

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#181]
**What version of the tools are you running, and how?**
v1.4.13, drag game json onto exe

**Is your feature request related to a problem? Please describe.**
There are scenarios where skaters need to be quickly added to a team's roster (esp in between -- or even during -- jams) with only the skater's number (not name). The rest of the scoreboard works fine in this case, but jamstats's reporting is less useful.

![image](https://github.com/user-attachments/assets/9c88e07e-838e-4c56-b3a9-7e303317e4a2)

**Describe the solution you'd like**
if a skater doesn't have a name, jamstats should just use the number as the "name" that gets displayed.

**Describe alternatives you've considered**
make my NSOs always add names; that's the ideal case, but it's not always practical

**Comment by dhmay** [comment]
@erevrav I believe I implemented this enhancement in the Windows build artifact [here](https://github.com/dhmay/jamstats/actions/runs/11492536392/artifacts/2097093446). Please test it out; if it looks good, I'll merge to main and make a new release.

**Comment by erevrav** [comment]
works great, thx!
![image](https://github.com/user-attachments/assets/d4b9e887-e99c-4235-8780-6369e9041065)
