### ISSUE TITLE
FR: Import data from filled-in statsbooks

### ISSUE THREAD

**Issue by kirajcg** [dhmay/jamstats#183]
Would it be possible to enhance the tool with the option to import data in not just json but xlsx format? Which is to say filled-in statsbooks. That way it could be a useful tool even when not using ePLT.

**Comment by dhmay** [comment]
That would be a fair chunk of work... would [this](https://github.com/AdamSmasherDerby/Statsbook-Tool) be a potential workaround? I haven't tried it out, myself -- I've never worked with statsbooks -- but it purports to load a statsbook xlsx and "save the game in DerbyJSON format, in case that proves useful for some reason". Maybe this is that reason!
