### ISSUE TITLE
change scary 'interruption can corrupt your data' text in 'stop task' dialog on exiting a live connection to scoreboard

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#184]
**What version of the tools are you running, and how?**
v3.4.14 directly connected to scoreboardserver

**Is your feature request related to a problem? Please describe.**
When jamstats is connected to a scoreboardserver (not importing data from a jsonfile), clicking the 'Stop' button in the jamstats window presents a scary popup that 'interruption can corrupt your data'. 

<img src="https://github.com/user-attachments/assets/a12df1c8-2853-46d8-a45a-bbbfe914d9f0" width=50%>

**Describe the solution you'd like**
When you've got a live connection, there's no threat of data corruption on exit (I hope). Having a warning here seems appropriate, but just the first sentence seems sufficient: "Are you sure you want to stop the task?"

**Describe alternatives you've considered**
I dunno. we could actually corrupt some data somewhere, if it indeed might? (kidding! I can imagine scenarios where jamstats could foul scoreboard data & I don't really even like joking about that.)

**Comment by dhmay** [comment]
I know you're kidding, but it's impossible for JamStats to foul the scoreboard data. The most harm I can imagine JamStats doing to the scoreboard is essentially DOSing it if too many people ran JamStats at once, but I've done a lot to minimize even that impact.

**Comment by dhmay** [comment]
@erevrav can you try the [executable](https://github.com/dhmay/jamstats/actions/runs/12024392560/artifacts/2236919985) in [this PR build](https://github.com/dhmay/jamstats/actions/runs/12024392560). I changed the "console" option in PyInstaller from False to True. My hope is that if it's got a console to spew scary messages to it won't do it in a prominent window, but I don't know.

I got rid of my last Windows box, so I don't have anything in the house I can try Windows-only changes like this on.

**Comment by erevrav** [comment]
nope, that presents a popup that's identical to the previous one. the pyinstaller-provided window has this:

> jamstats version 1.4.14, by Damon May
> Connecting to server 192.168.1.44, port 8000...
> Mode not specified. Inferred mode web
> Using theme white
> 
> Starting jamstats server...
> Point your browser to:  http://localhost:8080
> 
> Opened connection.
> 2024-11-25 22:23:28,210 | jamstats.io.scoreboard_server_io |  INFO: Opened connection.


and the cmd window where jamstats started has:
> jamstats version 1.4.14, by Damon May
> Starting GUI...
> Created parser. Adding args...
> Added args. Parsing args...

so, maybe I can't get what I'd like here. That's a weird choice, PyInstaller, that's a weird choice.

**Comment by dhmay** [comment]
Hey, I think I did it! I was wrong, earlier -- the dire warnings weren't coming from PyInstaller, but from Gooey, the package I'm using to wrap my commandline interface with a window. I got ChatGPT to help me figure out how to monkeypatch Gooey. I changed that dire message to simply: "Are you sure you want to stop?"

Should be fixed in [this EXE](https://github.com/dhmay/jamstats/actions/runs/12073925870/artifacts/2251109718). Can you please verify, @erevrav ? Any other messages you'd like changed while I'm at it? It's super easy now.

**Comment by erevrav** [comment]
woot! thank you!

> ![image](https://github.com/user-attachments/assets/ace5c314-7ced-4c2c-8b7e-cb199696a738)
