### ISSUE TITLE
before game starts (and generally, whenever we're not in a jam), show the best data we've got

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#185]
**What version of the tools are you running, and how?**
v3.4.14 directly connected to scoreboardserver

**Is your feature request related to a problem? Please describe.**
When you first connect jamstats to a live scoreboard & open the web page (but the first jam hasn't started), the big text suggests the connection isn't working: the Caller Dashboard page says "Can't display Caller Dashboard right now", Teams Summary says, "Can't display Teams Summary right now", etc. 

And because we don't show lineup data until the start of a jam, announcers can't get a pre-read on the skaters that are arriving for Jam 1.

The Team Roster and Officials Roster pages both show information, so clearly the connection is working. 

<img src="https://github.com/user-attachments/assets/3fd170fd-0015-472c-a314-7744a36c34e4" width=50%>

**Describe the solution you'd like**
Ideally, we'd automatically show text like "Game not started yet" along with the best pre-jam data we have available: the team & official rosters, then show the lineup data as it gets added by LTs or SBO. 

(the issue I'm reporting is most-important for the pre-game scenario, but depending on how you address the "not in a jam yet" case overall, I'd love to see the skater lineups as they get entered in between jam *n* and jam *n+1*

**Describe alternatives you've considered**
Worst, the page should really convey that jamstats is ready, it's just that game just isn't running. This would mitigate the user-confusion that causes my event staff to regularly come & report that IT'S BROKEN! even though IT'S ACTUALLY WORKING.

**Comment by dhmay** [comment]
@erevrav I implemented the "Worst" fix, i.e., tell the user that the game just isn't running. Forgot to make a branch -- please try out [this exe](https://github.com/dhmay/jamstats/actions/runs/12074301320/artifacts/2251209144). Note that that contains fixes for both your recent bugs. Once you confirm fix, if you don't have any related requests, I'll make a new JamStats release, so please do let me know one way or the other.

I don't fully understand the "Ideally" behavior you asked for. This is framed as a request for the Caller Dashboard, but you're asking for team & official rosters. Those are on separate UI pages. Are you saying that the Caller Dashboard should display the contents of both of those other UI pages when we're between games? That seems weird to me... if they want that data can't they just click over to those pages and then click back to the Dashboard?

**Comment by dhmay** [comment]
@erevrav based on our conversation this weekend, I don't think you saw the message above. Let me know if you vet those two bugfixes using the exe I linked above.

**Comment by erevrav** [comment]
The "Game hasn't started yet" text is way better than the previous version. You could legit declare good enough here, but I'll try to clarify my Ideally behavior for the Caller Dashboard screen.

Today, if I go to CRGs roster view (e.g., http://localhost:8000/views/roster/), I can see skaters getting selected even though the game hasn't started, so as an announcer I can fill some of my airtime talking about the skaters that have entered the track without waiting for the jam to start to get their names. 

here's what those two screen look like, pre-game:
> ![image](https://github.com/user-attachments/assets/e3ef0096-3e0c-4349-ad48-4d804af6f24a)

In between jams, CRG's roster page shows me the full lineup as it's being selected, so I can start talking about the upcoming skaters. Jamstats shows the "Next jam's jammer" before the new jam starts, so you're already doing *some* of what my Ideal case looked like (but I see none of it until the game starts, and only see the full lineup after the jam begins).

> ![image](https://github.com/user-attachments/assets/3cb42ac1-ef34-4cf2-8a50-93acae97134b)

And yes, I confirm the fix for #184. yay!
