### ISSUE TITLE
Add fun "anonymized" derby names

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#28]
Currently, the name anonymizer function spits out a random string of letters and numbers. Instead, use a whole bunch of names I already made up.

**Comment by erevrav** [comment]
I know you've already closed this ticket, but if eventually you're tired of the names from `ANONYMIZED_SKATER_NAMES`, you could see if there's an API onto https://twoevils.org/rollergirls/?c=0&r=1.
