### ISSUE TITLE
use team colors in charts instead of always "Blue" and "Orange"

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#32]
**What version of the tools are you running, and how?**
direct dump from dhmay via pdf

**Is your feature request related to a problem? Please describe.**
it's hard to tell which team data in an unexpected color goes with. Seeing a team I always associate with green displayed in orange bends my brain.

**Describe the solution you'd like**
for all the graphs that compare two teams, the colors would be way easier to follow if they reflected the team colors. Seeing `[a team I associate with blue]` displayed in blue and `[a team I associate with green]` displayed in orange was a memory test on basically every page.

- Good news: with our teams we only have 12 colors. (Maaaaybe 14, if our second travel team gets rolling again, but I don't know what colors they'll use)

- Bad news: if the background stays white, the team colors for white & yellow seem gratuitously hard, since they might need shadows or something to make them legible).

- Good news: black or gray background might be fine, as in my screencap.
![team-color-fragment](https://user-images.githubusercontent.com/26390183/208820378-23ced9c2-643c-436e-9300-d9ab69970b13.png)

You don't have to use the colors here, but they are conveniently in the json for each game, at the lines like
`"ScoreBoard.PreparedTeam(GreenTeam).Color(scoreboard_bg)" : "#4dff29"`
 if your engine lets you "just" switch the background to black (or #24292E which was the bgcolor in the screenshot from slack) would it make using our lighter team colors as defined in the file less cascade-prone? Might have to special-case travelteam.gray to something else, but maybe the others would work?

**Describe alternatives you've considered**
Being smarter? Suffering with the color-confusion? learning python well enough to fix it myself?

**Additional context**
as dhmay wrote in slack: 
`For colors: could work fine for all our teams' colors, but I'd worry that it wouldn't work for everyone (Team Midnight!). Easiest would probably be to expose a background color option on the commandline`

probably related to any fix for
https://github.com/dhmay/jamstats/issues/24

**Comment by dhmay** [comment]
Implemented, mostly. I'm not yet supporting different background colors, so Team White will be out of luck.

If I fail to find the team colors in the JSON file, I default to blue and orange.

**Comment by erevrav** [comment]
yaaaaaay, mah brain thanks you!
