### ISSUE TITLE
page 1 - show total minutes of play, like total number of periods & jams

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#33]
**Describe the bug**
on page 1, Minutes is 25 (the length of one period). Given that Periods is 2 and jams is 26, Minutes should be 50 minutes or something very close.

**To Reproduce**
looked at PDF data dump from 2022-12-18

**Expected behavior**
Minutes should be the sum of p1 and p2

**Comment by dhmay** [comment]
Fixed.
