### ISSUE TITLE
page 1 - show numbers without decimal places

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#34]
**Describe the bug**
Page 1 - it's weird to have decimals (e.g., "218.0") on this page, given that they're all integers.

**To Reproduce**
looked at PDF drop from dhmay on 2022-12-18

**Expected behavior**
Integers like scores & number of periods and so forth should display as integers.

**Comment by dhmay** [comment]
Fixed.

**Comment by erevrav** [comment]
yup
