### ISSUE TITLE
Page 1 - show number of skaters who actually played in a game

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#35]
**What version of the tools are you running, and how?**
data dump from dhmay 2022-12-18

**Is your feature request related to a problem? Please describe.**
Page 1 - among the stats here, it would be useful to see the number of skaters who actually played based on the lineup-tracking data (to clarify, that's not just the full team list in the roster).

**Comment by dhmay** [comment]
Added, but I added it to Page 2, since that's already broken out by team. Seemed cluttered on page 1.
<img width="480" alt="image" src="https://user-images.githubusercontent.com/714077/209451845-dd8cfb5f-97d2-4040-9443-5512754eb2c4.png">
