### ISSUE TITLE
page 2 - don't sum injury numbers

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#36]
**Describe the bug**
Page 2 - Jams that end with Injury accrue to both teams, so these numbers will always be identical (and they shouldn't be summed).

**To Reproduce**
looked at PDFs from 2022-12-18

**Expected behavior**
Injury data isn't per-team. A jam that ends with an Injury code is applied to both teams, so even if there's 5 injuries listed for each team, that's only 5 injuries. (Minimally, that's true with CRG v4; I assume it's true with v5, but we could always check to make sure they're the same & if at some point they aren't, maybe the software changed.)

**Additional context**
 As long as we call it out in the mail to coaches, I don’t think you'd need to fix it before the mail, but we should for some future version of the report:

**Comment by dhmay** [comment]
Do you think the "sum" column adds any value to that table? The only rows I think it might be interesting for are "calloff" and "starpass"... if you think those are worth keeping, I could move them to the first table. The rest are, as you indicate, confusing or useless.

**Comment by dhmay** [comment]
Oh, and if the injury numbers should be identical, then I should move the sum of those to the first table, too.

**Comment by erevrav** [comment]
> Do you think the "sum" column adds any value to that table?

you've already removed the column from the page, but I don't think any of them are particularly meaningful when summed, even calloff & starpass.

> Oh, and if the injury numbers should be identical, then I should move the sum of those to the first table, too. Right?

yeah, page1 feels like the right place for them. (I'm pretty sure there would have to be a WFTDA rules change to get Inj tracked per-team, so trying to get ahead of that kind of change seems silly).

**Comment by dhmay** [comment]
Fixed.

<img width="473" alt="image" src="https://user-images.githubusercontent.com/714077/209453085-95c3d38f-e573-420f-ac4d-0d543a2568ad.png">
