### ISSUE TITLE
page 3 - provide clearer visual landmarks in charts

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#37]
**What version of the tools are you running, and how?**
data drop from 2022-12-18

**Describe the solution you'd like**
Page 3 - I'd love a primary hairline on the graph separating period 1 from 2, and maybe secondary lines at every ~5 jams?

**Describe alternatives you've considered**
lines, shading

**Additional context**
this may be true for other charts than just page 3

**Comment by dhmay** [comment]
Let's not let the great be the enemy of the good. Added a hairline separating periods.
