### ISSUE TITLE
page 4 - columns should be in the order they're on scoresheets

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#38]
**Describe the bug**
Page 4 - Points per jam by team - columns are in non-standard order. 

**To Reproduce**
v0.1.7-alpha

**Expected behavior**
- columns should be in the order they're on scoresheets, with SP leftmost.
- maybe should use X in each column rather than other letters just like a scoresheet. Minimally, don't reuse L for both Lead and its near-opposite, Lost

**Screenshots**
![image (1)](https://user-images.githubusercontent.com/26390183/208827202-68e08477-e77e-451c-9a44-e14d2db5f13d.png)

**Additional context**

**Comment by dhmay** [comment]
Fixed. I called lost "O" and capitalized the O in the legend. I called Star Pass SP and No Initial NI.

**Comment by erevrav** [comment]
confirmed
