### ISSUE TITLE
Page 5 - don't split the "Points per jam per team" onto two pages by period 

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#47]
**Describe the bug**
Page 5 - there are two pages for "Points per jam by team" - it seems unnecessarily sparse to split these into two pages 

**To Reproduce**
v0.2.0-alpha

**Expected behavior**
for all the jams for the game to be on a single page.

**Comment by dhmay** [comment]
The reason I split it up is because the plot becomes *enormous* if I put the whole game on one plot. I don't have an example saved of how insane it was, but you can just imagine all that data on one page. 

Do you feel strongly about this? I could make it a commandline option.

**Comment by dhmay** [comment]
FYI, @erevrav , here's how it looks all together. The code is there to do this, and I could add a flag for it if you think it's important. I think this plot gets really hard to read.
![image](https://user-images.githubusercontent.com/714077/209448023-bf00e12c-e4c4-4bf8-ba51-574883946011.png)

**Comment by dhmay** [comment]
The other thing I could do is let it get arbitrarily long... like, it's 11" long now, I could let it get 22" long but still with the same width. That would make it difficult to use in some situations, like trying to display on a tablet screen all at once.
