### ISSUE TITLE
page 7 - making sense of the "Jams with Lead" chart is harder than it could be?

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#48]
**What version of the tools are you running, and how?**
v0.2.0-alpha 

**Is your feature request related to a problem? Please describe.**
we may need to chew on the "right" design here, but in a previous build lead was in gray, and I complained about it. In 0.2.0, got-lead-and-called is in team colors, got-lead-and-lost-it is red for both teams, and got-lead-and-ended-on-time is gray for both teams. Doing the apples-to-oranges on this stat is hard (for me, apparently)

**Describe the solution you'd like**
**_I don't know._** 

**Describe alternatives you've considered**
show the Called portion in the same color for both teams? don't use stacked bars (I'm pretty sure *that's* a terrible direction.)

**Comment by dhmay** [comment]
Do you not like the stacked bars? I like them because, summed, they let you visually compare total number of jams per team.

**Comment by dhmay** [comment]
Changed "lost" from red to black. Seemed more neutral.

**Comment by erevrav** [comment]
I meant to have a question mark at the end of "don't use stacked bars (I'm pretty sure that's a terrible direction.)" -- I considered it, but it would be a terrible direction. sorry for unfortunate typo.

**Comment by dhmay** [comment]
I'm gonna close this as non-actionable until we figure out a change we want.
