### ISSUE TITLE
Page 9 - unified "Penalty counts" page becomes visually unclear when one team doesn't have any of some penalty type

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#49]
**What version of the tools are you running, and how?**
v0.2.0-alpha

**Is your feature request related to a problem? Please describe.**
It's great that both teams are unified into a single chart now. But there are two cases that the current layout makes hard to grok. 
1. weird, but comprehensible with some staring: If just one team just doesn't have any of penalty in a block where both teams generally have them both. (e.g., Pink doesn't have any Directions, but if they'd just had 1, wouldn't be hard at all to measure one from the next.)
2. almost incomprehensible: the second team doesn't have one of a particular penalty, and the first team doesn't have any of the next kind in the list. (e.g., Making sense of each team's Illegal Procedures or Interferences is *way* harder than it is with Backblocks or Cuts. There isn't anything meaningful in weighing Pink's I's vs. Yellow's N's, but that's what happens.)
![image](https://user-images.githubusercontent.com/26390183/209276075-a1d11418-76d9-47e9-97a8-1759d0540756.png)

**Describe the solution you'd like**
some marker on the axis or in the plot area to delineate one penalty area from the next. An ugly version of that:
![image](https://user-images.githubusercontent.com/26390183/209276526-d9c2131f-982a-434d-9753-ccd42167a75b.png)

**Describe alternatives you've considered**
- some marker on the axis
- shading in the plot area
- stubby little just-a-few-pixel-long bars

**Additional context**
While I putatively created this problem by asking for the two teams to be displayed in a single chart, the current version is an improvement over that. Definitely wouldn't revert that change.

**Comment by dhmay** [comment]
Fixed.
<img width="620" alt="image" src="https://user-images.githubusercontent.com/714077/209451715-c490c2c5-6b55-497c-80ab-53e312bc7e38.png">
