### ISSUE TITLE
page 11 - visual guidance to whatever we think is important on Jammer Stats page

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#51]
**What version of the tools are you running, and how?**
v0.2.0-alpha

**Is your feature request related to a problem? Please describe.**
Page 11 - the relationship between # Jams, Total Score & Mean Net Points feels hard to glean understanding from. e.g., 
- At first glance, the two highest-scoring players for (Team A) had negative Mean Net Points. I *think* that's because they actually jammed more often than some of their teammates, but I'm not sure what to make of that information...
- Among the conclusions no-one should come to: negative mean net score is bad. At least, I _think_ that's right?

**Describe the solution you'd like**

**Describe alternatives you've considered**
if we think Mean Net Points is actually a useful stat, would its meaning be clearer if we sorted the skaters by that? or is it only vaguely-important, so sorting by that would cause coaches/fans/announcers/etc., to overindex on that? would sorting skaters by any of these columns be helpful? none particularly feels like it, but without being able to do it, I'm not sure.

**Additional context**

**Comment by dhmay** [comment]
Let me be clear about what Mean Net Points *means*: it's the mean number of *net* points that jammer scored per jam. By *net*, I mean that jammer's score minus the opposing jammer's score for that jam.

So, it's totally possible for the highest-scoring jammer to have lower Mean Net Points than other jammers. Depends on who they were up against.

Someone on the scoreboard FB group (can't remember who) specifically asked for Mean Net Points. I don't personally have a feel for how valuable it is as a stat, but at least someone thinks it's meaningful.

How to sort the jammers is a good question. Currently, it's not intentionally sorted by anything, which is clearly the wrong behavior. The top three things I think we might want to sort on, in my descending order of preference, are:

1. Jammer name
2. Jams jammed
3. Mean net points
4. Total points

**Comment by erevrav** [comment]
**MNP**
> jammer's score minus the opposing jammer's score

Holy heck. ok, I'm gonna have to chew on that a little, but I understand it now. Very different than what I expected. (can we burn footer text into some of these pages, for that kind of explanation?)

I wonder if there's some way (or value) to convey that Artemis Foul is great in jams against Sudden Beth, but less-good against Scarlight Express? I mean, the game isn't really jammer-on-jammer, and it's more about combination of jammer-plus-opposing-blockers, but if MNP is of value to the original poster, seeing that expansion *could* be relevant? I'd be super curious what the OP thinks.

**Sorting** 
By jams jammed seems useful (esp at our level) to help coaches see whether they're being intentional in their fielding of skaters. Like, did you mean to send Scarlight out 5 times and Scar The Grouch out only once? 

But if you sort by # of jams, we'll probably want a secondary sort, since that number is almost certainly going to be smaller than number of skaters, and we don't want "skaters who jammed 3 times" to be sorted randomly. Maybe first by # of jams, then by a stat you don't have here: average points per jam? (probably avg & not median, since that's more-readily grokkable & (probably) most skaters won't have an outlying jam making their average weird. See also, "Bill Gates Has A Really Good Jam").

**Comment by dhmay** [comment]
Sorted on jams, followed by total score to break ties. I could burn in longer explanatory text, but I'd rather avoid that if possible. What do you think about this longer X axis label on the Mean Net Points plot?

![image](https://user-images.githubusercontent.com/714077/209395681-2e63b635-4b44-4ad3-983f-0bca47f8425a.png)
