### ISSUE TITLE
allow me to fully-anonymize the output, for bug reports, documentation, etc.

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#52]
**What version of the tools are you running, and how?**
v0.2.0-alpha

**Is your feature request related to a problem? Please describe.**
I want to file bug reports without feeling like I might be embarrassing anyone from a real team. the `--anonymize` switch is great, but in some scenarios (bug reports, documentation, etc.), I don't even want the team names from the json to show up.

**Describe the solution you'd like**
A switch like `--anonymizefull` to do what `--anonymize` does, and also turns the team names into Team 1 and Team 2 

**Describe alternatives you've considered**
Extra credit: choose from your favorite list of fictional team names, at https://en.wikipedia.org/wiki/List_of_fictional_sports_teams or elsewhere.

**Comment by dhmay** [comment]
Fixed. Two flags, now, `--anonymize` (for skaters) and `--anonymizeteams` (for, uh, teams).
