### ISSUE TITLE
Page 12/13 - Skater Stats - penalty legend can occlude the number of penalties for some skaters

### ISSUE THREAD

**Issue by erevrav** [dhmay/jamstats#53]
**Describe the bug**
on Skater Stats pages, the penalty legend can occlude the number of penalties for some skaters

**To Reproduce**
v0.2.0-alpha

**Expected behavior**
the legend shouldn't block the data the page is trying to convey. I think Rebel Girl only got 5 penalties, but I'm not sure.

**Screenshots**
![image](https://user-images.githubusercontent.com/26390183/209284986-4c51d1e5-c33c-4930-bb6c-5960ecfa4c5e.png)

**Additional context**
move legend to the bottom? make the box yet more transparent?

**Comment by dhmay** [comment]
This one is really hard to figure out how to implement. Seaborn is already trying as hard as it can to avoid conflicts between legend and data, so we're not likely to make great strides there. Moving the legend off the plot is the classic solution, but it's hugely wasteful of space and could make everything hard to read. My favorite options are:

1. Abbreviate the penalty names even more, e.g., Illeg Pos
2. Nothing -- it's unfortunate when it happens but solvable by squinting
3. Reduce the font size on the legend

What do you think?

**Comment by dhmay** [comment]
Oh, one more option:

Sort jammers by the number of penalties they got. That's almost certain to leave a nice bit of whitespace on the lower right (or upper right, if we sort ascending) for the legend.

**Comment by erevrav** [comment]
> Sort skaters by the number of penalties they got

oooh, I like this option. Since the page is (mostly) about penalties, I'd sort descending and put the legend at the bottom right. That won't fix my issue *every* time, but it might be close.

**Comment by dhmay** [comment]
Got it. Merged to main. 

If you want to check it out before I do a release, go to Actions, click on [Merge pull request #54 from dhmay/enh](https://github.com/dhmay/jamstats/actions/runs/3767641866), scroll down to Artifacts, and download jamstats-plot-pdf-Windows. (after it finishes building.

![image](https://user-images.githubusercontent.com/714077/209393830-bed23172-8a34-48cd-a7d8-95ab31bbdc3a.png)
