### ISSUE TITLE
Add penalties/jam to skater plot

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#60]
Add penalties per jam to the skater plot.

**Comment by dhmay** [comment]
@erevrav I think is is an important new statistic. When just showing total penalties per skater, someone who was out there a ton looks like they're getting more penalties than someone who was accruing penalties at the same rate but was out there for just a few jams.

<img width="843" alt="image" src="https://user-images.githubusercontent.com/714077/209450144-8b96b5f2-4bb5-48ce-88d7-c7e3544dd6e1.png">

**Comment by dhmay** [comment]
For instance, in this game, Artemis Foul has the third most penalties, but they have by far the most penalties per jam.
<img width="846" alt="image" src="https://user-images.githubusercontent.com/714077/209450178-c70f6d04-c467-463f-9d45-c847b1337acb.png">

**Comment by erevrav** [comment]
> Artemis Foul has the third most penalties, but they have by far the most penalties per jam.

(Good job assigning random names, Anonymizer!)
