### ISSUE TITLE
BUGREPORT - Long derby names overlapping in WebServer display

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#67]
**Describe the bug**
In the WebServer display, longer team/league names are overlapping in the _Jammer Summary_ and _Team Summary_ outputs

**To Reproduce**
Ran the JamStats v0.3.4 exe via command line, with my local IP/Port for CRG and port 8003 for the webserver - Windows server 2019 64 bit. Also reproduced in Windows 11 64bit. Both using the latest version of Chrome

**Expected behavior**
Word-wrap the team/league names at the mid-point of the plot

**Screenshots**
![image](https://user-images.githubusercontent.com/28804763/210976096-6181fb7e-c368-4016-b506-ad6bbc59e9f8.png)
![image](https://user-images.githubusercontent.com/28804763/210976334-6abd3451-aa71-4be2-b79f-4f5028579252.png)

**Comment by dhmay** [comment]
Awright! I'm glad to see you're using the webserver! Have you connected to live games, or just opened json files? I hope to [display the IP](https://github.com/dhmay/jamstats/issues/66) of the webserver soon so it's easy to tell people what to connect to.

The name-wrapping thing should be easy with (note for future me) [textwrap](https://docs.python.org/2/library/textwrap.html)

**Comment by dhmay** [comment]
Fixed, I think. @bullseye555 , when [this build completes](https://github.com/dhmay/jamstats/actions/runs/3856816250), please grab the new jamstats.exe file and verify.

I wrapped team names at 15 characters, which hopefully is about right.

**Comment by dhmay** [comment]
Direct link to the Windows exe:
https://github.com/dhmay/jamstats/suites/10224634781/artifacts/501074225

**Comment by bullseye555** [comment]
![image](https://user-images.githubusercontent.com/28804763/211131721-2591a2ce-bd55-480d-8560-de7a3b1bd15e.png)

Looks much better
