### ISSUE TITLE
Can't connect to webserver from another machine

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#70]
**Describe the bug**
Reported by a Scoreboard group member on Facebook:
I can only access on the hosted device using 127.0.0.1:xxxx ; is this a JamStats limitation, the WebServer, or am I just doing something wrong ?

**Screenshots**
![image](https://user-images.githubusercontent.com/714077/211066988-532a28ef-e6b4-4556-b8d3-545968f42a33.png)

**Comment by dhmay** [comment]
I believe I've fixed this. I also am now notifying the user of the IP and port on which the server is running, both on the commandline (or the Gooey window) and in the webserver itself (bottom left):
<img width="732" alt="image" src="https://user-images.githubusercontent.com/714077/211134894-6a4d60cc-2858-4f93-9a94-968089b0cead.png">

You should now be able to access the server using the IP and port it tells you to use. Let me know if that works!

**Comment by bullseye555** [comment]
Success!

![image](https://user-images.githubusercontent.com/28804763/211143725-1e046c42-49a5-4bc4-9b99-6e904623e69b.png)

But localhost:8003 and 127.0.0.1:8003 don't connect. Not an issue, as 99.9999999999999% of people will use the device IP in the first place

(As a bonus, I learnt how to create this as EXE in GIT AND on my local PC today :P )
