### ISSUE TITLE
BUGREPORT - Connection to Scoreboard picking up incorrect game

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#72]
**Describe the bug**
When connecting to the scoreboard, it's not picking up the currently running game, but instead is picking up a game that is still listed as 'Running', but is not the live game

![image](https://user-images.githubusercontent.com/28804763/211133023-de1bb2bc-81a1-4c3a-808c-2f5c63825ac2.png)
I've also validated that the PDF output also uses the same game
![image](https://user-images.githubusercontent.com/28804763/211133052-eccb2586-b106-445e-b5a5-b914422b3df2.png)

**To Reproduce**
Running CRG with multiple loaded games, some of which are at _Running_ status instead of _Prepared_ or _Finished_
![image](https://user-images.githubusercontent.com/28804763/211133013-73e5326c-3d8f-4805-a633-a5b17509b5b4.png)

**Expected behavior**
It should connect to the current game

**Additional context**
Not sure exactly how you're connecting to CRG, but there's another project that connects to CRG that may be useful (this was developed by another Aussie, a Referee named Vector from Western Australia)
https://gitlab.com/project-6/p5-score-keeping/p5-scoring-gauntlet

**Comment by dhmay** [comment]
Oh, dear. The way I'm getting what I thought was the current game is:

http://{server}:{port}/SaveJSON/scoreboard-0-secs-ago.json

I guess that's not the current game! If you know offhand where to find the current game JSON on the scoreboard server, please point me to it! Otherwise, I'll dig into the link you pasted.

**Comment by bullseye555** [comment]
Ah-ha *lightbulb*

Are you extracting "ScoreBoard.CurrentGame.xxxxxx" nodes only?

As a secondary suggestion to this issues, there may be instances where a JSON file may have multiple games (eg: like the Scoreboard-0-secs-ago.json file). I'll drop a feature suggestion to be able to select the game if there's more than one game in a JSON file


The link I posted is using a Socket connection to CRG, rather than reading the JSON file each time - might be worthwhile as a future sprint if you wanted to update the connection methodology
> https://gitlab.com/project-6/p5-score-keeping/p5-scoring-gauntlet/-/blob/master/ScoringGauntlet.py
This has the _Connect_ function

**Comment by dhmay** [comment]
Fixed, I think. But I don't have any v5 in-progress games with much data in them (nor the expertise to dummy one up well), so I can't verify completely. But I now I'm grabbing the CurrentGame keys and throwing out the Game(x) keys.

Connecting via socket and getting incremental updates would somewhat reduce the burden on the scoreboard server (which I think isn't very high), but I'd have to do a moderate amount of work on the json parsing. I'll keep it in mind if it seems like there are good reasons to.

**Comment by dhmay** [comment]
If you're still seeing the data from the wrong game, please send me a file where this happens.

**Comment by bullseye555** [comment]
From the 3 CRG instances I'm running, I've confirmed it's now picking up the correct game for all 3

But as per #73 it looks like subsequent refreshes are broken
