### ISSUE TITLE
BUGREPORT - Total Game Time showing as a countdown

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#73]
**Describe the bug**
Total Game Time is showing as a count down from 60:00, rather than the elapsed game time

**To Reproduce**
![image](https://user-images.githubusercontent.com/28804763/211133326-22fc9859-b822-4ead-a607-e906f1039937.png)

**Expected behavior**
Should show total actual game time elapsed
I couldn't find a node in the JSON that had the total time elapsed, but I found a couple of nodes that will help with calculation

**( (Period(2).WalltimeEnd minus Period(2).WalltimeStart) + (Period(1).WalltimeEnd minus Period(1).WalltimeStart) )÷ 60000** ; then the **decimal value * 60** to give the number of minutes
![image](https://user-images.githubusercontent.com/28804763/211134454-03da06e5-e0fa-4ad7-b86f-39aea3b97b46.png)
![image](https://user-images.githubusercontent.com/28804763/211134465-6d1fcecf-7b98-45df-87e6-bd5c895592df.png)

_(1670048238248 -1670046203487) + (1670045276118-1670043099661) = 4,211,218 ÷ 60000 = 70.1869667 ; 0.1869667 * 60 = 11.2 == 70:11_
The last step can be skipped if there's a Python library that will convert Decimal to MM:SS 

This doesn't factor in Timeouts, so the Statistic name should be _Total Game Time including Timeouts_

Or if you want to exclude Timeout elapsed time too, it would be **( SUM(Period(1).Timeout(XYZ).Duration" : ######) + SUM(Period(2).Timeout(XYZ).Duration" : ######) )** where XYZ is the unique Timeout Identifier and ###### is the numeric duration

![image](https://user-images.githubusercontent.com/28804763/211134359-91fc1f44-3f86-47ae-ada6-f010f0b20563.png)

You would then subtract that value from before the ÷ 60000 in the first formula eg:
**( (Period(2).WalltimeEnd minus Period(2).WalltimeStart) + (Period(1).WalltimeEnd minus Period(1).WalltimeStart) - ( SUM(Period(1).Timeout(XYZ).Duration" : ######) + SUM(Period(1).Timeout(XYZ).Duration" : ######) )  )÷ 60000** ; then the **decimal value * 60** to give the number of minutes

_(1670048238248 -1670046203487) + (1670045276118-1670043099661)  - 388000 = 3,823,218 ÷ 60000 = 63.7203 ; 0.7203 * 60 = 43.2 == 63:43_

**Comment by dhmay** [comment]
Fixed, I believe, in branch bugfix6

**Comment by bullseye555** [comment]
Looks like the game time has been fixed, but between this patch and #72 it's now trying to connect to the wrong port when refreshing data

GUI Config
![image](https://user-images.githubusercontent.com/28804763/211174063-c57bb41e-f6c1-4af6-8934-b88b132bcc53.png)

Scoreboard, confirming the teams
![image](https://user-images.githubusercontent.com/28804763/211174068-7f914caf-8e65-4a43-a54d-32fb58cdcc0f.png)

Initial Load of WebServer page
![image](https://user-images.githubusercontent.com/28804763/211174078-f9ed5708-d62c-4555-a95d-2811ef7004ef.png)

Scoreboard prior to refresh (so scores should appear as 12 / 11 and at least 5:49 elapsed game time)
![image](https://user-images.githubusercontent.com/28804763/211174086-079fe436-12b7-4ecd-a6d7-04ddd78716eb.png)

WebServer page after refresh
![image](https://user-images.githubusercontent.com/28804763/211174110-94019a2d-f42c-4992-8c5f-dff3a847b312.png)

Jamstats logging showing it's attempting to connect to the right server & port initially, but right server & wrong port for refreshes
![image](https://user-images.githubusercontent.com/28804763/211174127-8b98ef47-f048-4b9b-99b4-dcb641791e64.png)

**Comment by bullseye555** [comment]
HAHAHAHA

Because I'm running my CRG server(s) on a different device to what I'm testing JamStats on, I can cheat and just set my WebServer port to be the same as the CRG port and it will refresh and show data as expected - 99.999999999% of people will be running it on the same device though, so can't do this (even I'd be doing that at a game or Tournament [difference being that my setup has CRG on a different device to what the Scoreboard Operator uses] )

Same game, several jams later with JamStats running on the same port as the CRG instance
![image](https://user-images.githubusercontent.com/28804763/211174391-4945832d-6b04-4c01-9a95-fa5830fe194a.png)

**Comment by dhmay** [comment]
Throwing a hail mary because I'm off to ref some derby. Please check out the build here when it completes:
https://github.com/dhmay/jamstats/actions/runs/3864598376

should fix the refresh port issue.

**Comment by dhmay** [comment]
@bullseye555 Another small tweak, that probably shouldn't matter to the problem at hand:
https://github.com/dhmay/jamstats/suites/10243349127/artifacts/502387496

Sorry I didn't see your PR before I tried fixing it, myself!

**Comment by bullseye555** [comment]
@dhmay - All good!

Confirming the refresh works with your update

Confirming this also fixes the issue I found in my PR

**Comment by dhmay** [comment]
Whew!

**Comment by bullseye555** [comment]
One thing I noticed in 0.4.0 (with fix from #89) is that the Game Time is only picking up what the game time is at the end of the Jam

`"ScoreBoard.CurrentGame.Clock(Period).InvertedTime"` seems to be the field to use

![image](https://user-images.githubusercontent.com/28804763/212445523-7d56bca4-dba9-40b1-a680-e6a87262d683.png)
