### ISSUE TITLE
BUGREPORT - Teams with same League Name rolled up on Game Summary

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#74]
**Describe the bug**
When two teams from the same league are in the game, the Game Summary page only has _one_ of them listed

**To Reproduce**
[STATS-2022-07-23_PotLuckAmber_vs_PotLuckAmber.json.txt](https://github.com/dhmay/jamstats/files/10365653/STATS-2022-07-23_PotLuckAmber_vs_PotLuckAmber.json.txt)

JSON attached, gives PDF output attached
[LiveGame_stats.pdf](https://github.com/dhmay/jamstats/files/10365655/LiveGame_stats.pdf)

**Expected behavior**
Both teams should be listed in the Summary page

**Comment by dhmay** [comment]
Heh. It's not just that they're the same league. They have the same name! From the json:

    "ScoreBoard.Game(ef5a8052-b186-4e9a-8ca6-f74ee2884c82).Team(1).Name" : "Pot Luck - Amber",
    "ScoreBoard.Game(ef5a8052-b186-4e9a-8ca6-f74ee2884c82).Team(2).Name" : "Pot Luck - Amber",

I'm tempted to call this "user error", but if this is a common thing to do, I'd better find some way to deal with it. In this file, it looks like the teams do have different "FullName":

    "ScoreBoard.Game(ef5a8052-b186-4e9a-8ca6-f74ee2884c82).Team(1).FullName" : "Pot Luck - Amber - Black",
    "ScoreBoard.Game(ef5a8052-b186-4e9a-8ca6-f74ee2884c82).Team(2).FullName" : "Pot Luck - Amber - White",

I'll shift to that, in the case where the team names are the same. But it will probably have downstream impacts that I'll have to sort out.

**Comment by dhmay** [comment]
I think I fixed this (on branch bugfix4 for now, will merge today). But the potluck file you sent didn't have a ton of game data, so I'm not sure I fixed the name-handling everywhere.

**Comment by bullseye555** [comment]
Looks good now.

It would be common for _Home Team_ games; eg: Brooklyn Bombshells vs Manhattan Mayhem for Gotham Roller Derby.

I'll keep an eye on this and reopen if I come across any more issues
