### ISSUE TITLE
BUGREPORT - Game Summary saying Final Score when game is in progress

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#81]
**Describe the bug**
In the _Game Summary_ it says **{team name} Final Score** even though the game is still in progress

**To Reproduce**
Connect to a running game

**Expected behavior**
The word _Final_ should only be populated if 
- When connected to SCOREBOARDSERVER the game has been flagged as finished
- If a JSON file is used as the import method

**Screenshots**
![image](https://user-images.githubusercontent.com/28804763/211174536-378e383b-6863-43da-886b-51279a2198d0.png)
![image](https://user-images.githubusercontent.com/28804763/211174532-ae7bb786-0d9e-4c26-b701-bb020ad71bb4.png)

**Additional context**
ScoreBoard.CurrentGame.State : "Finished" is what you're looking for (here's a FINISHED game example)
![image](https://user-images.githubusercontent.com/28804763/211174574-cf37d101-88aa-4033-ad27-b93a53b25443.png)
(Here it is in the CurrentGame of the other above screenshots)
![image](https://user-images.githubusercontent.com/28804763/211174591-0222eaf8-06ec-4f3c-9948-db93d8cd3fc1.png)

**Comment by dhmay** [comment]
Thanks for pointing me to the way to sort this out... I'll break the fields in the table up into "Game State", "Team 1 Score" and "Team 2 Score"

**Comment by dhmay** [comment]
You can check out the fix here:
https://github.com/dhmay/jamstats/actions/runs/3868472731

**Comment by bullseye555** [comment]
Looks good!! 

Confirmed that it changes from _Running_ to _Finished_ for a game that I've forced to end early
The only other test would be for _Prepared_ games when #84 is done. I'll reopen this if there's an issue once that's done (but I don't expect there to be
