### ISSUE TITLE
FR - Select NIC/IP address to start WebServer on

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#83]
I could have sworn I'd made a comment about this in another thread somewhere, but apparently not

**What version of the tools are you running, and how?**
Windows Server 2019 64bit / Windows 11 64 bit, via GUI (or occasionally CMD)

**Is your feature request related to a problem? Please describe.**
The problem is that I have a VM on my Server. When running JamStats, it's picking up the IP address of the VM NIC instead of the IP of the primary NIC [There is also a use case within my league where we have multiple NICs on a device, and at Tournaments, each track is on a different network]

**Describe the solution you'd like**
Within the GUI and CMD, have an option that would allow the input/selection of the IP address to use. 
My thought would be that a drop-down list is populated with the available IP address, and the user selects the one they want the WebServer to run on [Default option could be blank if that's easier, or pick the first IP address in numerical order (and the IP address would be ignored unless the JamStatsPort is populated)]

**Describe alternatives you've considered**
Having to disable and enable Network Interfaces every time to get the WebSever on the correct network is not practical - especially if the server is running multiple active games and it's only the JamStats that needs to be restarted

**Comment by dhmay** [comment]
I can super easily add an argument to specify the IP to serve on. I'll aim to do that today. The other stuff is beyond my expertise... i.e., figuring out what the actual options are. If you have some ideas about that, let me know.

**Comment by dhmay** [comment]
I did what I described above... reopen if you want to figure out how to give the user options for the IP.

**Comment by dhmay** [comment]
You can check out the fix here:
https://github.com/dhmay/jamstats/actions/runs/3868472731

**Comment by bullseye555** [comment]
Happy to leave it as an open editable field with the default being the previous action of "Let the WebSever pick the IP to use"

Have tested on Windows and validated :)
