### ISSUE TITLE
Make documentation for plot interpretation

### ISSUE THREAD

**Issue by dhmay** [dhmay/jamstats#85]
**Is your feature request related to a problem? Please describe.**
The one coach I've talked to so far finds the plots difficult to interpret. I suspect they're too "Data Sciency". I'm interested in potentially changing them to make them more accessible, but I also think some documentation would help.

**Describe the solution you'd like**
Build a powerpoint-ish deck explaining how to interpret each plot. Make a PDF version available on github.

**Comment by dhmay** [comment]
@bullseye555 @erevrav FYI. I'm interested in your thoughts on this, and also on your feedback on the PDF I'll make.

**Comment by dhmay** [comment]
Oh, I think better than a PDF (or maybe in addition) would be just to use annotated versions of the plots in the github readme.

**Comment by dhmay** [comment]
Added. You can see it all from the readme. Let me know what you think!

**Comment by bullseye555** [comment]
I think the plot samples and interpretation guide will be useful - as someone who (kindof) understands stats etc, they all make sense to me, but this will help for those that may need some assistance in understanding what they're seeing
