### ISSUE TITLE
FR - WebServer starts even if the game hasn't yet started

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#91]
**What version of the tools are you running, and how?**
0.4.0 (from #89) via EXE in Windows

**Is your feature request related to a problem? Please describe.**
Currently, if the Game has been setup in CRG but there has been no Jam (eg: Game starts at 2:30pm and it's now 2:15pm and we're getting the tech stuff ready for the game) the WebServer will fail to start
![image](https://user-images.githubusercontent.com/28804763/212445747-61d69bde-0ebc-448e-bb1d-c94ae2095c41.png)
![image](https://user-images.githubusercontent.com/28804763/212445751-3fbaa0e3-cb91-4ba0-828f-2b7e7e44ad23.png)
This means that on whatever machine the program is running, the Restart button will need to be engaged after the game starts. Not an ideal situation for multi-game day(s)/tournaments
![image](https://user-images.githubusercontent.com/28804763/212445785-372a63f9-f60c-4947-8000-0ed11c89617a.png)

**Describe the solution you'd like**
WebServer initialises and picks up the relevant _Game Summary_ details (JSON below of game in the above screenshot **before** any Jams were played)
Game Status and Scoreboard Version can both be populated, with all others either **0** or Blank
All other plots should provide no information (Blank plots, with just Team Names? Or blank pages if that's easier)
[scoreboard-0-secs-ago__202301141244.json.txt](https://github.com/dhmay/jamstats/files/10416340/scoreboard-0-secs-ago__202301141244.json.txt)

**Describe alternatives you've considered**
I was hoping this may have only been an issue for the first game of the day & track, but I've found another bug when testing how JamStats behaves if a new game is started

**Comment by dhmay** [comment]
OK, I think I've fixed this in [this PR](https://github.com/dhmay/jamstats/actions/runs/3920141013).

Now, you can start up the jamstats server and see the web interface even if the scoreboard server hasn't been started yet -- it'll say "no game data". It'll refresh every 30 seconds, and whenever the server is available the game will show up.

**Comment by bullseye555** [comment]
Looks good!

Also - worked out whey I was getting the _DataFrame_ error - teams had no players loaded. I don't expect you should have to handle this, as the likelyhood of a game with no loaded players using JamStats is slim-to-none

![image](https://user-images.githubusercontent.com/28804763/212521674-d84edcb5-07aa-447d-a3ea-b00b6e6124a3.png)
![image](https://user-images.githubusercontent.com/28804763/212521677-37b1a7c8-28e5-4319-95c8-e08b00981c77.png)
