### ISSUE TITLE
BUG - WebServer game doesn't update to the CurrentGame if the game changes - WebServer appears to crash

### ISSUE THREAD

**Issue by bullseye555** [dhmay/jamstats#92]
**Describe the bug**
As per title. When a new game is started in the Scoreboard, the WebServer appears to crash

**To Reproduce**
Run a game in CRG while using 0.4.0 EXE in Windows. Complete the game and then start a new game [simulating a multi-game scenario]
JamStats debug window shows `Failed to download in-game data from server 172.24.10.200:8001: 'DataFrame' object has no attribute 'Id'` and the _Last Updated_ time doesn't change [Regardless of _Auto Refresh_, Manual Refresh (F5) or Force-Refresh (CRTL+F5)]

Also get the same error if JamStats is _Stopped_ and the _Restarted_

**Expected behavior**
WebServer output picks up the next game and displays stats (as per #91 , if the game hasn't yet started, this should still display a game, but with 0 data)

**Screenshots**
![image](https://user-images.githubusercontent.com/28804763/212446366-ac2a21a0-5799-488d-bb5c-57be2bb63c57.png)
![image](https://user-images.githubusercontent.com/28804763/212446379-916499b0-d431-4992-b584-8dc3f91470d5.png)

**Additional context**
JSON attached with old game and new game
[scoreboard-0-secs-ago__202301141312.json.txt](https://github.com/dhmay/jamstats/files/10416357/scoreboard-0-secs-ago__202301141312.json.txt)

**Comment by dhmay** [comment]
OK, I *think* what's actually going on here has nothing to do with the switch of game and everything to do with the new game not having enough data yet for me to load a DerbyGame object.

So, I think [this PR](https://github.com/dhmay/jamstats/actions/runs/3920141013) will probably address the issue. Now, when you switch to a new game, it'll just say "no game data" and keep refreshing until it successfully loads a game, and then charts will show up. Let me know if that's what happens, and if this behavior seems right!

**Comment by bullseye555** [comment]
The PR fixes the issue - but doesn't behave as you've described

Previous "Current" game
![image](https://user-images.githubusercontent.com/28804763/212521931-1d01d60f-b4fe-4786-84ec-fcbdfcb88a26.png)

New "Current" game, with the red line in the debug window showing where the games change was
![image](https://user-images.githubusercontent.com/28804763/212521938-28d27adc-2949-483c-b471-b503bc28d895.png)

Second refresh after game change. Red line in debug shows where the game change was, Scoreboard showing expected team names [ or "No game data" ] and WebServer still showing previous game
![image](https://user-images.githubusercontent.com/28804763/212521955-6f410cd8-25bc-436b-bf38-0d2205ef1033.png)

JSON screenshot confirming CRG has the "new" game as the CurrentGame
![image](https://user-images.githubusercontent.com/28804763/212521991-1c5e961f-2e83-4888-b5ff-d2bed602cdb4.png)

I haven't taken screenshots, but I have confirmed that once the new game starts [first Jam is initiated] that it switches to the new game

Other than the incorrect Game Status of the previous game, I personally don't have an issue with this behaviour - allows teams to review their data immediately after the game before it refreshes into the new game

**Comment by dhmay** [comment]
Interesting! Thanks for letting me know about that behavior. I guess the server maintains the previous game as "CurrentGame" until the next game starts. That's kind of weird, but... ok!
