### ISSUE TITLE
PDF export doesn't have correct jammer names

### ISSUE THREAD

**Issue by atkinsonm** [dhmay/jamstats#98]
**Describe the bug**

The PDF export contains what look like default/canned jammer names, but the browser version from the same CRG export has the correct names.

**To Reproduce**

1. Get a CRG game export
2. Upload it to the site
3. Compare the PDF and browser versions of the jammer point graphs

**Expected behavior**

The correct jammer names show on the graph in the PDF export

**Screenshots**

Browser: 
<img width="633" alt="image" src="https://user-images.githubusercontent.com/3342243/216149380-cccbe1d2-5e1b-4dca-81c2-066205aedc2c.png">

PDF:
<img width="922" alt="image" src="https://user-images.githubusercontent.com/3342243/216149502-d1308965-4de5-473a-9a8c-c4d6493c6325.png">

**Additional context**

**Comment by dhmay** [comment]
Fixed! Thank you for pointing that out! I have an "anonymizer" function, and I had accidentally defaulted it to On rather than Off,

**Comment by atkinsonm** [comment]
Thanks for the super fast fix!
